title: 'Rental Application'
honeypot: lastname
fields:
  Check-In-Date:
    display: 'Check in date - Saturday'
    validate: required
  Check-Out-Date:
    display: 'Check out date'
    validate: required
  Name:
    display: Name
    validate: 'required|min:2'
  Email:
    display: 'Email address'
    validate: required|email
  Home-Phone-Number:
    display: 'Home Phone number'
  Cell-Phone-Number:
    display: 'Cell phone number'
  Address:
    display: Address
  City:
    display: City
  Province-State:
    display: Province/State
  PostalCode-ZipCode:
    display: 'Postal Code - Zip Code'
  Number-of-Years-at-Address:
    display: 'Number of years at address'
  Owner-Renter:
    display: Own/Rent
    validate: required
  Employer:
    display: "Employer's Name and Address"
  Job-Title:
    display: 'Job Title'
  Length-of-Employment:
    display: 'Length of Employment at Current Job'
  Drivers-License:
    display: "Driver's License - Province/State and Number"
  License-Plate:
    display: "Vehicle License Plate - Province/State and Number"
  Insurance-Provider:
    display: 'Home/Renter Insurance Provider'
  Policy-Number:
    display: 'Policy Number'
  Number-of-Adults:
    display: 'Number of adults'
    validate: required
  Number-of-Children:
    display: 'Number of children'
    validate: required
  Occupant-Info:
    display: 'Names, Addresses and Phone Numbers of ALL adults and children occupying Bakerâ€™s Landing, including the ages of all children'
  Bringing-Dog:
    display: 'Are you bringing a dog?'
    validate: required
  Dog-Info:
    display: "Please provide details of age, breed, size, temperament and training. Please note Baker's Landing has a strict maximum 2 dog policy, and cats are not allowed."
  Bringing-Guests:
    display: 'Are you bringing additional guests?'
    validate: required
  Guest-Info:
    display: 'If yes, please provide their names and dates of their visit.'
  Bringing-Boat:
    display: 'Do you plan on bringing a boat? If so we have plenty of parking space.'
    validate: required
  Comment:
    display: 'Please use the area below to add any additional Details, Questions or Comments you may have.'
columns:
  - Check-In-Date
  - Check-Out-Date
  - Name
  - Home-Phone-Number
  - Email
  - Cell-Phone-Number
  - Address
  - City
  - Province-State
  - PostalCode-ZipCode
  - Number-of-Years-at-Address
  - Owner-Renter
  - Employer
  - Job-Title
  - Length-of-Employment
  - Drivers-License
  - License-Plate
  - Insurance-Provider
  - Policy-Number
  - Number-of-Adults
  - Number-of-Children
  - Occupant-Info
  - Bringing-Dog
  - Dog-Info
  - Bringing-Guests
  - Guest-Info
  - Bringing-Boat
  - Comment
email:
  -
    to: whitehouseont@gmail.com
    from: info@bakerslanding.ca
    reply_to: '{{email}}'
    subject: 'BL - Rental Application Submission'
